branch-defaults:
  react:
    environment: wire-account-staging
  staging:
    environment: wire-account-staging
  master:
    environment: wire-account-prod
deploy:
  artifact: dist/wire-account.zip
global:
  application_name: Account
  default_platform: Node.js
  default_region: eu-central-1
  sc: git
  workspace_type: Application
