branch-defaults:
  master:
    environment: wire-account-prod
  staging:
    environment: wire-account-staging
  team-create:
    environment: wire-account-staging
deploy:
  artifact: dist/wire-account.zip
global:
  application_name: Webapp
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
